-- ============================================================================
-- EMHA DONASI - SUPABASE (POSTGRESQL) DATABASE SCHEMA & RLS POLICIES
-- ============================================================================

-- 1. TABEL DONATUR (donors)
CREATE TABLE IF NOT EXISTS public.donors (
    id TEXT PRIMARY KEY,
    nama TEXT NOT NULL,
    hp TEXT,
    provinsi TEXT,
    kabupaten TEXT,
    kecamatan TEXT,
    kelurahan TEXT,
    alamat_maps TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL TRANSAKSI DONASI MASUK (donations)
CREATE TABLE IF NOT EXISTS public.donations (
    id TEXT PRIMARY KEY,
    donor_id TEXT REFERENCES public.donors(id) ON DELETE SET NULL,
    nama TEXT NOT NULL,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    jumlah NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    tujuan TEXT NOT NULL,
    metode TEXT NOT NULL DEFAULT 'Transfer',
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL PENGELUARAN KAS / OPERASIONAL (expenses)
CREATE TABLE IF NOT EXISTS public.expenses (
    id TEXT PRIMARY KEY,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    kategori TEXT NOT NULL,
    jumlah NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    metode TEXT NOT NULL DEFAULT 'Tunai',
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL KATEGORI KAS MASUK (categories_masuk)
CREATE TABLE IF NOT EXISTS public.categories_masuk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL KATEGORI KAS KELUAR (categories_keluar)
CREATE TABLE IF NOT EXISTS public.categories_keluar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABEL KERANJANG SAMPAH / SOFT DELETE (trash)
CREATE TABLE IF NOT EXISTS public.trash (
    id TEXT PRIMARY KEY,
    item_type TEXT NOT NULL,
    item_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    deleted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABEL AKUN ADMIN & PENGATURAN (admin_account)
CREATE TABLE IF NOT EXISTS public.admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE DEFAULT 'admin',
    password TEXT NOT NULL DEFAULT 'admin123',
    email TEXT NOT NULL DEFAULT 'admin@emhadonasi.com',
    phone TEXT DEFAULT '0895393181822',
    name TEXT DEFAULT 'Bendahara EMHA',
    app_theme TEXT DEFAULT 'navy',
    signature_base64 TEXT,
    profile_photo_base64 TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES (Mengizinkan Akses Anon Key)
-- ============================================================================

ALTER TABLE public.donors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories_masuk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories_keluar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trash ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_account ENABLE ROW LEVEL SECURITY;

-- Kebijakan Akses Penuh untuk Public / Anon
DROP POLICY IF EXISTS "Public Anon All Donors" ON public.donors;
CREATE POLICY "Public Anon All Donors" ON public.donors FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Anon All Donations" ON public.donations;
CREATE POLICY "Public Anon All Donations" ON public.donations FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Anon All Expenses" ON public.expenses;
CREATE POLICY "Public Anon All Expenses" ON public.expenses FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Anon All Cat Masuk" ON public.categories_masuk;
CREATE POLICY "Public Anon All Cat Masuk" ON public.categories_masuk FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Anon All Cat Keluar" ON public.categories_keluar;
CREATE POLICY "Public Anon All Cat Keluar" ON public.categories_keluar FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Anon All Trash" ON public.trash;
CREATE POLICY "Public Anon All Trash" ON public.trash FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Anon All Admin" ON public.admin_account;
CREATE POLICY "Public Anon All Admin" ON public.admin_account FOR ALL TO anon USING (true) WITH CHECK (true);

-- ============================================================================
-- SEED DATA AWAL
-- ============================================================================

-- Kategori Masuk Default
INSERT INTO public.categories_masuk (nama) VALUES
('Wakaf Jariyah'),
('Zakat'),
('Infaq'),
('Shodaqoh'),
('Dana Riba')
ON CONFLICT (nama) DO NOTHING;

-- Kategori Keluar Default
INSERT INTO public.categories_keluar (nama) VALUES
('Operasional Kantor'),
('Penyaluran Santunan'),
('Logistik & Sarana'),
('Penyaluran Wakaf'),
('Gaji & Honor')
ON CONFLICT (nama) DO NOTHING;

-- Akun Admin Default
INSERT INTO public.admin_account (id, username, password, email, phone, name, app_theme) VALUES
(1, 'admin', 'admin123', 'admin@emhadonasi.com', '0895393181822', 'Bendahara EMHA', 'navy')
ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    password = EXCLUDED.password;

-- Sampel Donatur Awal
INSERT INTO public.donors (id, nama, hp, provinsi, kabupaten, kecamatan, kelurahan, alamat_maps) VALUES
('DNR-001', 'H. Mile & Hj. Masita', '081234567891', 'JAWA TENGAH', 'KOTA SEMARANG', 'PEDURUNGAN', 'PEDURUNGAN KIDUL', 'Jl. Pedurungan Raya No. 12'),
('DNR-002', 'Ibu Lulu', '081234567892', 'JAWA TENGAH', 'KOTA SEMARANG', 'BANYUMANIK', 'BANYUMANIK', 'Jl. Banyumanik Indah No. 5'),
('DNR-003', 'Ibu Siti Rahayu', '081234567893', 'JAWA TENGAH', 'KOTA SEMARANG', 'TEMBALANG', 'TEMBALANG', 'Perum Tembalang Asri Blok B'),
('DNR-004', 'Bp Sumadi', '081234567894', 'JAWA TENGAH', 'KOTA SEMARANG', 'CANDISARI', 'CANDISARI', 'Jl. Candi Prambanan No. 8'),
('DNR-005', 'Ibu Tri Isti Rahayu', '081234567895', 'JAWA TENGAH', 'KOTA SEMARANG', 'GAJAHMUNGKUR', 'GAJAHMUNGKUR', 'Jl. Gajahmungkur No. 20')
ON CONFLICT (id) DO NOTHING;

-- Sampel Donasi Awal
INSERT INTO public.donations (id, donor_id, nama, tanggal, jumlah, tujuan, metode, catatan) VALUES
('DON-20260801-001', 'DNR-001', 'H. Mile & Hj. Masita', '2026-08-01', 1500000.00, 'Wakaf Jariyah', 'Transfer', 'Wakaf pembangunan gedung EMHA'),
('DON-20260802-002', 'DNR-002', 'Ibu Lulu', '2026-08-02', 1000000.00, 'Zakat', 'Transfer', 'Zakat Maal Penghasilan'),
('DON-20260803-003', 'DNR-003', 'Ibu Siti Rahayu', '2026-08-03', 250000.00, 'Infaq', 'Tunai', 'Infaq operasional dakwah'),
('DON-20260804-004', 'DNR-004', 'Bp Sumadi', '2026-08-04', 500000.00, 'Shodaqoh', 'Tunai', 'Sedekah subuh berkah'),
('DON-20260805-005', 'DNR-005', 'Ibu Tri Isti Rahayu', '2026-08-05', 200000.00, 'Dana Riba', 'Transfer', 'Penyucian dana jasa giro')
ON CONFLICT (id) DO NOTHING;

-- Sampel Kas Keluar Awal
INSERT INTO public.expenses (id, tanggal, kategori, jumlah, metode, catatan) VALUES
('EXP-20260802-001', '2026-08-02', 'Operasional Kantor', 450000.00, 'Transfer', 'Tagihan Listrik & Air Kantor EMHA'),
('EXP-20260805-002', '2026-08-05', 'Penyaluran Santunan', 1000000.00, 'Tunai', 'Santunan 10 Anak Yatim & Dhuafa'),
('EXP-20260810-003', '2026-08-10', 'Logistik & Sarana', 500000.00, 'Transfer', 'Pengadaan Al-Qur''an & Sound System'),
('EXP-20260815-004', '2026-08-15', 'Penyaluran Wakaf', 1200000.00, 'Transfer', 'Bantuan Pengeboran Sumur Air Bersih'),
('EXP-20260818-005', '2026-08-18', 'Gaji & Honor', 300000.00, 'Tunai', 'Honor Pemateri Kajian Pekanan')
ON CONFLICT (id) DO NOTHING;
